questions = [
    "He sido descuidado(a) con cosas que me prestan.",
    "Cumplo con todas las reglas y leyes.",
    "Cuando estoy con otras personas hablo en voz alta para que se fijen en mí.",
    "Me siento con más energía, sin tener razones.",
    "Sé lo que las personas piensan sin que me lo digan.",
    "Me impacienta cuando tengo que esperar mucho tiempo en una fila.",
    "Soy capaz de controlarme en todo tipo de situaciones.",
    "Es difícil para mí organizar las responsabilidades que tengo.",
    "Mantengo distancia de todas las personas.",
    "Me he sentido muy dolido(a) aún por cosas pequeñas que me han hecho.",
    "Las personas pierden la paciencia conmigo porque soy muy insistente.",
    "He sentido que soy otra persona.",
    "Me cuesta concentrarme.",
    "Tomo riesgos para que mi vida sea más emocionante.",
    "Me han dicho que tengo costumbres poco comunes.",
    "He dejado tiradas cosas que estoy haciendo, porque se me ocurrió hacer algo más interesante.",
    "Tengo sueños que me avisan sobre cosas que van a pasar.",
    "Disfruto mi facilidad para convencer a la gente.",
    "Me siento feliz.",
    "Miento para obtener lo que quiero.",
    "Es mejor no involucrarse en los problemas de otras personas.",
    "Me lleno de responsabilidades por ayudar a otros, y eso me cansa.",
    "Tengo más energía que las demás personas.",
    "Es difícil para mí hacer nuevas amistades.",
    "Siento que otras personas pueden leer mis pensamientos.",
    "Me es imposible controlar el enojo cuando me siento estresado(a).",
    "Me importa poco cuando otros se sienten mal por lo que hago.",
    "Se me dificulta concentrarme en las cosas que hago.",
    "Aunque me lastimen mucho, reacciono con tranquilidad.",
    "Hago mis tareas con tranquilidad, aunque me estén supervisando.",
    "Creo que soy un fracasado(a).",
    "Resuelvo hasta los problemas más difíciles con poco esfuerzo.",
    "Cuando me siento mal hago cosas de las que luego me arrepiento.",
    "Las personas hacen lo que quiero con solo pensarlo.",
    "Me preocupo tanto que todo se me hace insoportable.",
    "Hago lo posible por complacer a las personas.",
    "Me cuesta entender mis propios pensamientos.",
    "He engañado a algunas personas.",
    "Me afectan las críticas o lo que otras personas piensan de mí.",
    "Tengo muy claros mis planes y metas a futuro.",
    "Me han hecho cosas que me hacen desconfiar de la gente.",
    "Busco destacar entre las demás personas.",
    "Por más problemas que tenga, soy positivo(a) con lo que pasa en mi vida.",
    "En medio de una conversación he olvidado lo que tenía pensado decir.",
    "Algunas personas me han criticado injustamente por lo que he hecho.",
    "Me divierten los chismes y hablar a espaldas de otras personas.",
    "Veo los colores más brillantes que otras personas.",
    "Me meto en problemas cuando estoy enojado(a).",
    "Puedo pasar mucho tiempo haciendo algo sin tener que parar a descansar.",
    "He inventado problemas familiares para evadir obligaciones.",
    "Siento que no puedo controlar mi enojo.",
    "He tenido problemas con mi familia por tomar alcohol.",
    "Me he vengado de personas que me hacen enojar.",
    "Tomo riesgos mientras no sean excesivos.",
    "Creo que mi vida sin pareja no tiene sentido.",
    "Evito los lugares donde hay muchas personas.",
    "Me molesto cuando las personas no están de acuerdo conmigo.",
    "He convencido a personas para que hagan algo que yo quiero.",
    "Me gusta sentir que la gente se fija en mí.",
    "Quienes me conocen bien me han dicho que soy imprudente.",
    "Me han dicho que cambio de ánimo muy fácilmente.",
    "He mentido solo por el gusto de hacerlo.",
    "He dicho malas palabras.",
    "Me he levantado sin ganas de ir a trabajar o a estudiar.",
    "Confío en la mayoría de las personas que conozco.",
    "Me gusta relacionarme con personas que hacen cosas nuevas y diferentes.",
    "Tengo que estar preparado(a) por si alguna persona me traiciona.",
    "Busco nuevas experiencias como visitar lugares que no conozco.",
    "He aparentado estar triste para manipular a otras personas más fácilmente.",
    "Me esfuerzo por evitar actividades grupales.",
    "Estando dormido(a) he soñado con cosas que cuando estoy despierto(a) terminan haciéndose realidad.",
    "Disfruto menos las cosas que antes me gustaban.",
    "Aun estando furioso(a), soy paciente con los demás.",
    "He sentido atracción física por personas que no eran mi pareja.",
    "Digo que sí a todo para que la gente no se aleje de mí.",
    "Mis pensamientos desaparecen de mi cabeza sin que yo pueda controlarlo.",
    "Estando enojado(a) he sido cruel con otras personas.",
    "Soy tan impaciente que se me hace difícil seguir con orden las tareas que debo realizar.",
    "Prefiero estar solo que con otras personas.",
    "Me cuesta demostrar afecto o cariño a las personas.",
    "He faltado a citas, reuniones o compromisos si no tengo ganas de ir.",
    "He estado tan nervioso(a) que no he podido dormir.",
    "Puedo saber lo que pasará en el futuro.",
    "Algunas personas se han puesto de acuerdo para hacerme daño.",
    "Me considero una persona muy optimista.",
    "He tenido problemas en el trabajo por mi consumo de alcohol u otras sustancias.",
    "Mantengo relaciones amorosas, aunque estas me hagan sentir peor.",
    "He inventado alguna enfermedad o problema para huir de un compromiso.",
    "Las personas que me conocen han dicho que soy manipulador(a).",
    "Me han dicho que tengo pasatiempos poco comunes.",
    "Me molesto cuando me dicen lo que tengo que hacer.",
    "Necesito dormir menos horas que las demás personas.",
    "He probado la marihuana.",
    "He sentido como si mi alma abandonara mi cuerpo.",
    "Me encanta ser el centro de atención en fiestas o eventos.",
    "A pesar de estar enojado(a) o asustado(a) puedo actuar con cuidado.",
    "Soy sincero(a) con las personas, aunque eso perjudique mis intereses.",
    "Me obligo a terminar la tarea que estoy haciendo, aunque no tenga sentido que siga.",
    "Reacciono con cólera cuando me involucran en un chisme.",
    "He perdido relaciones con personas cercanas por una reacción repentina.",
    "Me considero una persona solitaria.",
    "Hago las cosas solo(a), aunque ocupe ayuda.",
    "Algunas personas han robado pensamientos de mi cabeza.",
    "He dicho cosas que a otras personas les asusta.",
    "Me han dicho que mi forma de hablar es extraña o no se entiende.",
    "Miento con facilidad y nadie se da cuenta.",
    "Tomar decisiones importantes me pone nervioso(a).",
    "He sido grosero(a) con personas que me han provocado.",
    "Me gusta estar rodeado(a) de muchas personas.",
    "He tomado decisiones sin pensar mucho en las consecuencias.",
    "Me siento mal por las cosas que he hecho.",
    "He deseado que algo malo le ocurra a alguna persona que no me agrada.",
    "Me asusto fácilmente.",
    "He tenido amistades que consumen algún tipo de droga.",
    "Me es difícil aceptar cuando me equivoco.",
    "Las personas afectan mi ánimo por cualquier cosa.",
    "Soy exitoso(a) en todo lo que me propongo hacer.",
    "He fingido simpatía para que la gente me ayude en alguna tarea.",
    "De tantos nervios, he sentido que me voy a morir.",
    "Los objetos a mi alrededor de repente me parecen extraños.",
    "Procuro decir la verdad, aunque eso me traiga problemas.",
    "Las personas que me conocen me han dicho que les demuestro mi aprecio.",
    "Me enojo cuando las cosas no salen como espero.",
    "Me tiene sin cuidado el reconocimiento de la gente cuando hago algo.",
    "Mis gustos para vestir son muy diferentes a los de las demás personas.",
    "Tengo problemas para dormir por tanta tensión.",
    "En las fiestas tomo más de tres bebidas alcohólicas.",
    "He hecho cosas peligrosas, aunque ponga en peligro mi vida.",
    "He juzgado a alguna persona solo por su aspecto físico.",
    "Tengo buena habilidad para planear cosas con tiempo.",
    "Cuando hago algo por demasiado tiempo, me aburro y me pongo a hacer otra cosa.",
    "Me afecto emocionalmente cuando personas cercanas me abandonan.",
    "He sacado provecho de mi relación con otras personas.",
    "He hablado mal de algún ser querido. ",
    "De tanta intranquilidad me ha costado concentrarme.",
    "Es sencillo ocultar mi tristeza cuando me siento afligido(a).",
    "Me cuesta mantenerme concentrado(a) en una sola cosa a la vez.",
    "Me pongo impaciente cuando estoy en charlas o reuniones de cualquier tipo.",
    "Pienso que el mundo sería un lugar mejor si yo muriera.",
    "Me cuesta respirar cuando estoy bajo mucha tensión.",
    "Cuando leo algo por mucho rato, me aburro y me pongo a hacer otra cosa.",
    "Me esfuerzo poco cuando realizo un trabajo.",
    "Durante una conversación me he distraído y perdido el hilo de lo que estaba hablando.",
    "Me molesta tener que estarle diciendo a las personas cómo se hacen las cosas.",
    "Me han dicho que soy una persona con sentimientos “fríos”.",
    "El consumo de alguna bebida alcohólica me ayuda a sobrellevar mis problemas.",
    "Invento historias para obtener algún beneficio propio.",
    "Siento alegría muy intensa sin tener clara la razón.",
    "En momentos de mucha energía hago cosas peligrosas como si nada pudiera pasarme.",
    "Gasto mucho dinero comprando bebidas alcohólicas.",
    "Me he vestido de forma llamativa para que la gente note mi presencia.",
    "Siento como si una parte de mi cuerpo hubiera sido cambiada.",
    "He contado a alguien un secreto que otra persona me confió.",
    "Me afecta que critiquen mi trabajo.",
    "Halago a las personas para que luego me ayuden.",
    "Paso de estar muy contento(a) a muy triste de un momento a otro.",
    "He sentido la presencia de alguien que las demás personas no pudieron sentir.",
    "He comprado cosas que no necesito, solo porque en ese momento me gustaron.",
    "He sentido fuerzas negativas a mi alrededor.",
    "He dejado de cumplir con tareas pendientes cuando se ponen difíciles.",
    "Le he gritado a alguien por contradecirme.",
    "He inventado mis propias palabras.",
    "Cuando me siento bajo mucha presión tomo alcohol.",
    "Trato mal a las personas cuando estoy estresado(a).",
    "Me he aprovechado de algunas personas.",
    "Evito perder mi tiempo escuchando a personas que saben menos que yo.",
    "Me han criticado por llegar tarde a compromisos.",
    "La vida es muy triste.",
    "He fingido estar enfermo(a) para evitar una responsabilidad.",
    "Pienso que tengo un “don especial” que las demás personas no tienen.",
    "Me ofende que no me atiendan inmediatamente cuando voy a comer a algún lugar.",
    "Necesito consumir alcohol u otras sustancias para sentirme mejor.",
    "Si mintiendo obtengo lo que quiero, no dudo en hacerlo.",
    "Me siento de repente muy emocionado(a) sin ninguna razón.",
    "Soy una persona muy emocional.",
    "Me gusta conocer gente nueva.",
    "Incluso las cosas más simples pueden hacer que me enfurezca.",
    "Si me emociono por algo se me pasa rápido.",
    "He tenido la sensación de que algo camina dentro de mi cuerpo.",
    "Dejo botadas algunas actividades o proyectos si se ponen difíciles.",
    "Reunirme con amistades que no veía hace mucho tiempo no me emociona.",
    "Otras personas me han dicho que me comporto de forma extraña.",
    "He sentido olores que otras personas no pueden notar.",
    "He consumido bebidas alcohólicas varios días seguidos.",
    "Hablo lo menos posible cuando estoy con otras personas.",
    "Me emociona visitar lugares que podrían ser peligrosos.",
    "Tiendo a hacer las cosas de la misma manera, aunque sepa que no va a funcionar.",
    "Me impacienta las personas que hablan mucho.",
    "Cuando me enojo con alguien no le hablo por mucho tiempo.",
    "Necesito hacer muchas actividades para poder liberar energía.",
    "Me cuesta compartir información con otras personas por temor a que la usen en mi contra.",
    "Me siento humillado cuando me critican por lo que sea.",
    "Me han puesto trampas para hacerme quedar mal.",
    "En situaciones de emergencia mantengo la calma.",
    "Me descontrolo cuando tengo mucha presión.",
    "He inventado cosas sobre mí para parecer más interesante ante los demás.",
    "Me ha hecho gracia cuando algún desconocido se ha tropezado y cae.",
    "Involucro a las personas que conozco en actividades que me benefician.",
    "He perdido amistades por consumir alcohol o drogas.",
    "La gente envidia mis cualidades.",
    "Evito correr riesgos innecesarios.",
    "Me ha interesado probar la marihuana u otras drogas.",
    "Invento cosas sobre mí mismo(a) para conseguir lo que quiero.",
    "Me cuesta disfrutar las cosas porque paso angustiado.",
    "Pienso que no sirvo para nada.",
    "Me gusta andar en vehículos a alta velocidad.",
    "Tengo pensamientos que las demás personas no entienden.",
    "Mis emociones son más intensas que las de otras personas.",
    "Me aburre vivir en el mismo lugar mucho tiempo.",
    "Cuando algo se me pierde sospecho de todas las personas a mi alrededor.",
    "Es difícil que me hagan cambiar de opinión, aunque pueda estar equivocado(a).",
    "Las fiestas me hacen sentir incómodo(a).",
    "Es mejor mentir si eso les evita dolor a las personas.",
    "Me da igual cómo me sienta emocionalmente.",
    "He hablado de forma grosera con otras personas.",
    "Disfruto haciendo quedar mal a la gente.",
    "He sentido miedo sin tener un motivo claro.",
    "Cuando me enojo por algo me cuesta mucho olvidarlo.",
    "He perdido las ganas de esforzarme por mis cosas.",
    "Me preocupo tanto que no puedo hacer bien las cosas.",
    "Me mantengo tranquilo incluso en situaciones de mucha presión.",
    "Evito tratar con personas menos importantes que yo.",
    "Me preocupo tanto que podría volverme loco(a).",
    "Manejo bien la presión cuando realizo mis obligaciones.",
    "Trato de ser cariñoso(a) con las personas que aprecio.",
    "He exagerado sobre mis capacidades para conseguir lo que quiero.",
    "La gente se aprovecha de mí.",
    "Las personas son fáciles de manipular.",
    "Pierdo horas de sueño por realizar tareas hasta terminarlas.",
    "Me siento nervioso(a) alrededor de otras personas.",
    "Creo que soy menos importante que los demás.",
    "Tomo mis decisiones luego de un análisis detallado.",
    "He comido algo aún sin saber exactamente lo que es.",
    "Cuando estoy de mal humor cualquier cosa pequeña me molesta.",
    "Me pone nervioso(a) hablar con personas importantes.",
    "Me emociona tener varias parejas a la vez.",
    "Me organizo tan bien que termino las cosas a tiempo.",
    "Me cuesta iniciar tareas que no me gustan, aunque sean urgentes.",
    "Comienzo hablando de un tema y cuando me doy cuenta hablo de otro que no tiene nada que ver.",
    "Me cuesta mantener mi cabeza centrada en lo que debo hacer.",
    "Me siento alegre.",
    "Quienes me conocen bien suelen confiar plenamente en mí.",
    "He intentado quitarme la vida.",
    "Desconfío de las personas demasiado amables.",
    "Me cuesta mucho saber cómo se sienten las personas a mi alrededor.",
    "Soy capaz de terminar con amistades o relaciones que me parecen dañinas.",
    "He conseguido drogas con facilidad.",
    "Mi forma de ser no es del agrado de algunas personas.",
    "Puedo controlarme cuando estoy enojado(a).",
    "Cuando me despido de un grupo de amigos pienso que hablan mal de mí.",
    "Pienso que, con todas mis cualidades, debería haber logrado más cosas.",
    "He llegado a pensar que tengo un problema con el consumo de licor.",
    "Siento tensos mis músculos cuando me enojo.",
    "Me cuesta estar calmado(a) cuando hago tareas importantes o complicadas.",
    "He dicho groserías a familiares sin sentirme mal por eso.",
    "Le he gritado a otras personas estando molesto(a).",
    "He sido tan desordenado(a) que me ha costado salir adelante con mis responsabilidades económicas.",
    "Tiro objetos estando enojado(a).",
    "He sentido envidia por personas que tienen algo que yo quiero.",
    "Hago cosas estando muy enojado(a) que después no puedo recordar con claridad.",
    "Me distraigo fácilmente cuando veo televisión.",
    "Me asombra la cantidad de cosas que sé.",
    "A la gente le cuesta trabajo entenderme.",
    "Me enoja que las cosas no me salgan bien al primer intento.",
    "Si quiero hacer algo, lo hago, aunque sea peligroso.",
    "Me he desquitado con personas que me han hecho algún daño.",
    "La gente habla mal de mí a mis espaldas.",
    "He sentido como si me moviera más despacio que las cosas a mi alrededor.",
    "Algunas personas tratan de controlar mis pensamientos.",
    "Me cuesta controlar algunas de las cosas que como, a pesar de que me hacen daño.",
    "He perdido oportunidades importantes por ser tan obstinado(a).",
    "Prefiero los trabajos en los que no tengo que tratar con muchas personas.",
    "Acepto mis errores con facilidad.",
    "Me molesta no ser reconocido(a) por mis logros.",
    "Me siento satisfecho(a) con lo que he logrado.",
    "Tengo tanta energía que siento que puedo lograrlo todo.",
    "He mentido en un negocio si la ganancia era grande.",
    "He actuado sin pensar bien las cosas y después me he arrepentido.",
    "Me siento incómodo(a) cuando alguien me comenta sus preocupaciones o problemas.",
    "Está bien engañar a las personas si así obtengo lo que quiero.",
    "Es difícil para mí pasar de una actividad a otra.",
    "Le echo la culpa a los demás para que se sientan culpables y así obtener lo que quiero.",
    "He hecho cosas tan extrañas que ni yo mismo me lo esperaba.",
    "Me aprovecho de la gente que es fácil de utilizar.",
    "Gasto mi dinero solo en cosas estrictamente necesarias.",
    "Me importa poco cuando alguien se siente mal por lo que yo le digo.",
    "Me han dicho que soy una persona malhumorada.",
    "Personas cercanas me han dicho que bebo más de la cuenta.",
    "Me siento muy mal cuando estoy solo(a) en la casa, aunque sea por poco tiempo.",
    "Cuando tengo algún problema pienso que ocurrirá lo peor.",
    "Trato de manera justa a todas las personas por igual.",
    "He dejado sin terminar algo y me he puesto a hacer otra cosa.",
    "Busco realizar tareas donde la gente me admire.",
    "Me preocupa mucho no saber si voy a terminar las cosas a tiempo.",
    "Siento que algo horrible me va a pasar.",
    "Me han dicho que soy una persona desconfiada.",
    "Otras personas pueden escuchar lo que estoy pensando.",
    "Me relaciono con la gente solo cuando es necesario.",
    "Evito contarle a la gente lo que pienso para que no piensen que soy raro.",
    "Escucho voces que nadie más puede.",
    "He pensado seriamente que quisiera morirme.",
    "Le hago caso a las voces que escucho en mi cabeza.",
    "Me ha tocado ser el(a) más inteligente de las personas con las que trato.",
    "Se me dificulta mentirle a los demás.",
    "He vivido situaciones difíciles que las demás personas no podrían entender.",
    "Me gusta participar en actividades en las que pueda sobresalir.",
    "He sentido como si el tiempo estuviera detenido.",
    "Suelo pasar mucho tiempo tratando de resolver algo, aunque no parezca tener solución.",
    "Cuando tengo que decir que no, lo hago, aunque las personas se enojen conmigo.",
    "Paso emocionalmente tranquilo(a) la mayor parte del día.",
    "Me es difícil dejar de realizar una tarea, aun cuando ya no tengo tiempo para seguir haciéndola.",
    "Evito que las personas se sientan en confianza conmigo.",
    "He consumido drogas ilegales.",
    "Creo que tarde o temprano me voy a suicidar.",
    "Me desquito con otras personas cuando estoy enojado(a).",
    "Oculto mis errores para que nadie se entere de mis debilidades.",
    "Me paralizo o bloqueo cuando trabajo bajo presión.",
    "La mayoría de la gente actúa sin malas intenciones.",
    "Consumir alcohol me ha causado problemas con personas cercanas.",
    "Evito las actividades en las que las personas se pongan muy emotivas.",
]
